Diseño segunda entrega
JuanOrtizz/Programacion_Web_I_Mate-Style pull request #2
Opened 2024-09-16 21:02 UTC by JuanOrtizz

> [!IMPORTANT]
> Diseñe con CSS todos los archivos HTML. Utilizando distintas practicas vistas en la unidad (display grid, display flex, box model, mediaqueries, etc.).
> Se puede guiar desde el prototipo proporcionado en el readme, para comparar el diseño realizado.

2024-09-16 22:26 UTC, JuanOrtizz commented
Profe una consulta. Porque en mi repositorio local, los estilos se aplican bien, mientras que en Pages no:
![image](https://github.com/user-attachments/assets/7115c012-d249-4fc2-9694-0642341fb3e2)

2024-09-25 15:27 UTC, MVelasquez98 commented
Fijate Juan de ver en el previsualizador del inspector de chrome para ver como se ve responsivamente según el tamaño de la pantalla del dispositivo, es más exacto que achicar la ventana.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6807d0b2-ad67-4272-b2e7-99f18a72dfb8">

2024-09-25 15:30 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Mejoras en la Maquetación CSS (5 puntos):**
- Implementación eficaz de diferentes tipos de selectores y aprovechamiento de la herencia de estilos para simplificar el código CSS. (1 punto) ✔️
- Aplicación correcta de formatos y fuentes para mejorar la legibilidad y estética del contenido, utilizando las propiedades CSS correspondientes. (1 punto) ✔️
- Uso adecuado de modelos de caja (box model) para controlar el tamaño, margen, relleno y bordes de los elementos de la página. (1 punto) ✔️
- Diferenciación clara entre elementos en línea y elementos en bloque mediante estilos CSS apropiados, demostrando comprensión de las diferencias y su aplicación en el diseño web. (1 punto) ✔️
- Implementación efectiva de columnas utilizando técnicas como elementos flotantes, display: flex y display: grid, según corresponda al diseño requerido. (1 punto) ❌ Falta el uso de Grid para la estructura de la pagina.

**Diseño de Columnas y Layouts Responsive (2 puntos):**
- Correcta utilización de media queries para crear un diseño responsive que se adapte de manera adecuada a diferentes tamaños de pantalla y dispositivos. (1 punto) ✔️
- Estructuración satisfactoria de layouts utilizando contenedores, filas y columnas, demostrando comprensión de los conceptos de diseño responsivo y su aplicación práctica. (1 punto) ⚠️ Podes ver como se vería tu página en un celular desde el inspector de chrome o el navegador que utilices

**GitHub (3 puntos):**
- Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto) ✔️
- Creación de una rama "feature/segunda-entrega" a partir de la rama "develop" utilizando Git. (1 punto) ✔️
- Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/primera-entrega" con "develop" en GitHub. (1 punto) ✔️

**Nota:** 9 (Nueve)

2024-09-30 21:49 UTC, JuanOrtizz commented
@MVelasquez98 

Implementación efectiva de columnas utilizando técnicas como elementos flotantes, display: flex y display: grid, según corresponda al diseño requerido. (1 punto) ❌ Falta el uso de Grid para la estructura de la pagina. 

Profe, con esto se refiere a que falta el grid para estructurar el header, main y footer? o que nunca utilice grid, ya que en varias paginas utilice el grid.
Por ejemplo:
![image](https://github.com/user-attachments/assets/c6436d2a-9a3c-461f-9b6b-ff2dec9e8fee)

Por eso mi consulta, muchas gracias y disculpe la molestia.
Saludos!

2024-10-01 18:50 UTC, MVelasquez98 approved these changes
LGTM
Juan, fue un error lo de la corrección en Grid. Disculpa

2024-10-02 03:52 UTC, JuanOrtizz commented
Perfecto profe, muchas gracias, disculpe la molestia :)

2024-10-02 16:39 UTC, merged