Release/primer parcial
JuanOrtizz/Programacion_Web_I_Mate-Style pull request #3
Opened 2024-10-02 19:46 UTC by JuanOrtizz

> [!IMPORTANT]
> Instale la biblioteca Bootstrap, colocando los links en todos los archivos .HTML. 
>
>Gracias a esta biblioteca, introduje un carrusel con imágenes con información importante y el eslogan de la empresa en el INDEX.HTML.
>
>También introduje un acordeón en las preguntas frecuentes, realizándolo ahora ya que me lo permitía la propia librería. Mi idea era hacerlo yo cuando veamos JS, pero al ver la documentación de Bootstrap, encontré esta funcionalidad y decidí implementarlo ahora.
>
>Por ultimo utilice Grid system de Bootstrap (container, row y col) en la estructura de una tabla, que agregue en INDEX.HTML, que me simplifico la tarea de tener que hacerlo responsive, como hice anteriormente con toda la estructura. La pagina quedo prácticamente responsive, viendo desde el inspector con F12 y cambiando las pantallas de los dispositivos como los distintos iPhones, Samsung, etc. Como me recomendó en la segunda entrega.
> 
>En cuanto al HTML, agregue un Iframe en INDEX.HTML con un vídeo de como un artesano realiza los mates que la empresa vende.
>
>Ademas realice modificaciones en archivos .HTML y el STYLES.CSS para organizar mejor el codigo y borrar algunas lineas que ya no iba a utilizar gracias a la libreria.

2024-10-04 18:24 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Incorporación de Componentes Avanzados de HTML (1 punto):**

- ✅  Agregar al menos un componente avanzado de HTML a la página, como un iframe de un video de YouTube o un mapa de Google Maps. (1 punto).

**Implementación de Bootstrap para Diseño Responsivo (5 puntos):**

- ✅ Instalar la biblioteca Bootstrap en el proyecto. (1 punto)
- ✅ Utilizar el sistema de columnas de Bootstrap para hacer que el sitio sea más responsivo en dispositivos móviles. (3 puntos).
- ✅Incluir al menos un componente avanzado de Bootstrap, como un carrusel, una barra de navegación o un modal. (1 punto)

**Gestión del Proyecto con GitHub (4 puntos):**

- ✅ Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto)
- ✅ Creación de una rama "release/primer-parcial" a partir de la rama "develop" utilizando Git. (1 punto) 
- ✅ Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/segunda-entrega" con "develop" en GitHub. (1 punto)
- ✅ Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama "release/primer-parcial" como parte de la entrega. (1 punto)

**Nota:** 10 (Diez)

2024-10-04 18:24 UTC, MVelasquez98 commented on index.html
> +        <nav><!--Nav donde se encuentra  una lista con cada una de las distintas secciones del menu-->
Quizas podrías usar un componente de Bootstrap [navbar](https://getbootstrap.com/docs/4.0/components/navbar/) aca. Para evitar que se vea así en dispositivos moviles.
![image](https://github.com/user-attachments/assets/dfdf5c43-aae7-491a-bead-7afdacc2422e)
Con este componente el menu se vuelve responsive. 
![image](https://github.com/user-attachments/assets/988bcd8b-38b4-47a2-9ba7-b388b5704b4a)

2024-10-15 15:16 UTC, JuanOrtizz commented
> [!NOTE]
>
> Hola @MVelasquez98, cambios realizados en el < header >, para mejorar la UX de los usuarios al interactuar con la aplicación web. Solicito LGTM.
> Saludos!

2024-10-15 17:26 UTC, MVelasquez98 approved these changes
LGTM

2024-10-21 15:19 UTC, merged