3ra entrega
JuanOrtizz/Programacion_Web_I_Mate-Style pull request #5
Opened 2024-10-21 19:38 UTC by JuanOrtizz

>[!IMPORTANT]
>Hola profe, a continuación dejo la PR de la rama feature/tercera-entrega, contra la rama Develop.
>
>En esta entrega se lleva a cabo la implementación de Javascript al proyecto.
>Donde realice varias funciones, dentro de un archivo **script.js**, asociado al **index.html**. En el futuro cuando tengamos que asociar estas funcionalidades a los elementos HTML, se va a realizar la asociación necesaria a cada archivo HTML.
>
>También cree un archivo **Producto.js**, el cual es una clase que posee un constructor y un método para obtener la información de cada instancia de este clase, es decir de cada producto. También quería consultarle si existe la herencia en JS como le menciono en una parte del código dentro del archivo **Producto.js**.

>[!NOTE] 
>Dentro del **script.js** hay un bucle do-while (temporal, solo para esta entrega) para mostrar por consola y por un pop-up **alert**, todas las funcionalidades implementadas en esta entrega. También se reciben entradas del usuario por otro pop-up, **prompt**.

2024-10-24 17:28 UTC, MVelasquez98 commented on Producto.js
> +//Una consulta es si hay herencia en JS, y si es posible utilizarla, para cada tipo de producto, para asi diferenciar mas especificamente cada uno de estos
Es posible si, utilizar herencia en JS.
https://developer.mozilla.org/es/docs/Learn/JavaScript/Objects/Classes_in_JavaScript#herencia

2024-10-24 17:48 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Algoritmos (1 punto)**
✅ 1 punto: Uso correcto y eficiente de algoritmos condicionales y ciclos.

- **Funciones (1 punto)**
✅ 1 punto:  Funciones con nombres claros, estructura correcta y resultados correctos.

- **Funcionalidad (1 punto)**
✅ 1 punto: Flujo de trabajo completo y funcionalidad apropiada al contexto.  Código JavaScript correctamente referenciado y uso adecuado de prompt() y alert().

- **Interactividad (1 punto)**
⚠️ 0-0.5 puntos: Interactividad insuficiente o salidas incoherentes. Revisar si se puede mejorar el uso del menu, al menos para las opciones. Para una primera interacción, costo hasta que no vi en el codigo la opción 9 y pude abrir la consola, para ver el resto de la interacción. 

- **Escalabilidad (1 punto)**
✅ 1 punto: Uso adecuado de funciones con parámetros, arrays y objetos relevantes.

- **Legibilidad (1 punto)**
✅ 1 punto: Nombres significativos, código legible y bien estructurado.

**GitHub (4 puntos):**
- ✅ 1 punto: Creación de una rama "backport/primer-parcial" a partir de la rama "master" utilizando Git.
- ✅ 1 punto: Creación de una rama "feature/tercera-entrega" a partir de la rama "develop" utilizando Git.
- ✅ 1 punto: Correcta realización de la solicitud de revisión para fusionar la rama "backport/primer-parcial" con "develop" en GitHub, resolviendo los conflictos de merge (si fuese necesario).
- ✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "release/primer-parcial" con "master" en GitHub,  resolviendo los conflictos de merge (si fuese necesario).

**Nota**: 9(Nueve)

2024-10-24 17:48 UTC, MVelasquez98 commented on script.js
> +    console.log("---Menu de Opciones---")
Este menu es dificil de visualizar, porque no puedo abrir la consola, sin sacar el prompt.
Se puede usar una concatenación para mostrar dentro del prompt las opciones:

> let opciones = 
> `---Menu de Opciones---
> 1-Filtrar producto por precio\n
> 2-Crear un producto nuevo\n
> 3-Agregar un producto al carrito\n
> 4-Ver tu carrito\n
> 5-Quitar producto del carrito\n
> 6-Ver productos\n
> 7-Modificar el nombre de un producto\n
> 8-Modificar el precio de un producto\n
> 9-Salir\n`;
> 
> let opcionMenu = parseInt(prompt(opciones + "Selecciona una opción e ingresa el número de la misma: "));

2024-10-24 17:48 UTC, MVelasquez98 commented on script.js
> +            console.log(productoCarrito.imprimirInformacion())
Considera usar [console.table() ](https://developer.mozilla.org/en-US/docs/Web/API/console/table_static)para mostrar los productos en el carrito o los productos disponibles. Esto puede hacer que la información sea más legible.

2024-10-24 17:48 UTC, MVelasquez98 commented on script.js
> +function crearNuevoProducto(){
Podrías validar que el nombre no esté vacío y que el precio sea un número válido antes de agregar el producto.

2024-10-25 18:06 UTC, JuanOrtizz commented
>[!NOTE]
>Hola @MVelasquez98, ya estarian todos los cambios solicitados.
>Pero antes de solicitar el LGTM quiero consultarle por lo siguiente:
![image](https://github.com/user-attachments/assets/44bde77e-0251-49db-b71f-a773ae3458df)
>Espero una respuesta.
>Saludos!

2024-10-28 14:36 UTC, MVelasquez98 commented on script.js
> +    //cual es mas conveniente usar, asignarle un nuevo arreglo vacio, cambiar la longitud a 0 o hacer un splice(0)?
- Si no tenes referencias activas al array, asignar un nuevo array vacío (carrito = [];) es lo más conveniente.
- Si tenes referencias activas al array (por ejemplo, si pasas el carrito a otras funciones o componentes), entonces es mejor cambiar la longitud a 0 (carrito.length = 0) para vaciar el array original sin romper referencias.
- El splice(0) modifica el array original, lo que es útil si existen referencias activas al array. Aunque esta opción es funcional, es la más costosa en términos de rendimiento, porque internamente mueve todos los elementos fuera del array, lo que puede ser ineficiente con arrays grandes.

2024-10-28 14:37 UTC, MVelasquez98 approved these changes
LGTM

2024-10-29 12:38 UTC, merged