Feature/cuarta entrega
JuanOrtizz/Programacion_Web_I_Mate-Style pull request #6
Opened 2024-11-19 20:36 UTC by JuanOrtizz

2024-11-21 19:11 UTC, MVelasquez98 reviewed
Esto es más a nivel UI:
![image](https://github.com/user-attachments/assets/04afec15-76e6-4635-9fe2-d60c3193e242)
¿No sería más intuitivo poder setear la cantidad? O quizas para no complejizar el algoritmo que al menos se visualice un solo producto con una leyenda que indique la cantidad

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +//FUNCIONES QUE SE AGREGARAN CUANDO EXISTA EL PANEL ADMIN
Noté que hay bloques de código comentado que no se están utilizando. Aunque entiendo que puede ser útil guardar este código temporalmente, no es una buena práctica dejarlo en el repositorio principal. Esto puede dificultar la lectura y el mantenimiento del código en el futuro, especialmente para otros miembros del equipo.

Si quieres conservar ese código para posibles referencias, puedes aprovechar Git para mantenerlo seguro. Por ejemplo:

- Guardarlo en una rama auxiliar local para tenerlo a mano sin comprometer el código principal.
- También podrías utilizar stash si los cambios son temporales y no están listos para incluirse en una rama formal.

De esta manera, mantenemos el código limpio y seguimos las buenas prácticas para garantizar un proyecto más organizado y fácil de mantener.

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +    if(emailElemento, mdpElemento, totalElemento){
El uso de la coma , en la condición actual no verifica si los elementos son válidos; en su lugar, siempre se evaluará como verdadero. Se deben usar condiciones con && para asegurar que todos los elementos sean válidos al mismo tiempo.

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        alert("El precio mínimo debe ser un número mayor o igual a 0")
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Considera mostrar los mensajes de error en el formulario en lugar de usar ventanas emergentes. Podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [SweetAlert](https://sweetalert2.github.io/)

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +    let productosFiltrados = false
Mover la declaración de let productosFiltrados fuera del bloque de función. Al inicializar let dentro de la función sin volver a usarla fuera, será redundante en caso de que desees verificar su estado en otros contextos dentro de la función.

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +    const patron = /^[^\s@]+@[^\s@]+\.[^\s@]+$/ // patron regex para comprabar esto con el test
Cambiar `const patron = /^[^\s@]+@[^\s@]+\.[^\s@]+$/ `a `const patron = /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.`  Esto mejorará la robustez de la validación del correo electrónico, aceptando más caracteres comunes.

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +function inputTelefono(texto){
Podes simplificar la función eliminando el uso explícito del if-else y retornando directamente la condición. Por ejemplo:
`function inputTelefono(texto) {
    return texto.length >= 10 && texto.length <= 11;
}
`

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +// funcion para verificar si el DNI es valido
Podes simplificar la función eliminando el uso explícito del if-else y retornando directamente la condición

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +function selectOpciones(opcionSeleccionada){
Podes simplificar la función eliminando el uso explícito del if-else y retornando directamente la condición

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +function inputNumTarjeta(texto){
Podes simplificar la función eliminando el uso explícito del if-else y retornando directamente la condición

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +    if(fechaVencimiento < hoy){ // si la fecha recibida por parametros es menor a la de hoy retorna false
Podes simplificar la función eliminando el uso explícito del if-else y retornando directamente la condición

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +function inputCVC(texto){
Podes simplificar la función eliminando el uso explícito del if-else y retornando directamente la condición

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +const carrito = JSON.parse(localStorage.getItem('carrito')) || []
Usar una clase para el carrito: Implementa una clase para encapsular la lógica del carrito. Esto mejora la reutilización y la claridad. Por ejemplo:
```

class Carrito {
    constructor() {
        this.productos = JSON.parse(localStorage.getItem("carrito")) || [];
    }

    guardar() {
        localStorage.setItem("carrito", JSON.stringify(this.productos));
    }

    agregar(nombre, precio) {
        if (!esProductoValido(nombre, precio)) return;
        // Lógica de agregar...
    }

    // Otras funciones...
}
```

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        const nombre = nombreFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        //valida el email
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        const telefono = telefonoFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        const dni = dniFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        const formaPago = formaPagoFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +            const cuotas = cuotasFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        const numTarj = numTarjetaFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        const nombreTitular = nombreTitularFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        const fechaVenc = fechaVencimientoFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:11 UTC, MVelasquez98 commented on script.js
> +        const cvc = cvcTarjetaFormulario.value
¿No puede ser una función auxiliar para limpiar un poco el código?

2024-11-21 19:15 UTC, MVelasquez98 reviewed
Cuesta quizas probar bien la funcionalidad de filtros por precio porque son todos el mismo precio:
![image](https://github.com/user-attachments/assets/676cf567-52ab-4b38-83ed-b9131974231d)

2024-11-21 19:22 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Funcionalidad (2 puntos)**
✅ 1 punto: Simula uno o más flujos de trabajo en términos de entrada, proceso y salida. Falta una salida final al usuario al finalizar la compra.
✅ 1 punto: La funcionalidad es apropiada al contexto del simulador y carece de errores de cómputo durante el procesamiento.

- **Interactividad (2 puntos)**
✅ 1 punto: Captura entradas ingresadas por el usuario mediante eventos.
✅ 1 punto: Efectúa una o más salidas por HTML modificando el DOM, con control de ingreso de entradas y salidas coherentes en relación a los datos ingresados.

- **Escalabilidad (2 puntos)**
✅ 0.5 puntos: Declara funciones con parámetros para definir instrucciones con una tarea específica.
✅ 0.5 puntos: Emplea arrays para agrupar valores relacionados.
⚠️ 0.25 puntos: Define objetos con propiedades y métodos relevantes al contexto. Pensar en utilizar una clase Carrito.
✅ 0.5 puntos: Establece un criterio homogéneo para la detección de eventos y almacena en storage datos relevantes generados durante la simulación.

- **Integridad (1 punto)**
✅ 0.5 puntos: Define el código JavaScript en un archivo .js, referenciándolo correctamente desde el HTML.
❌  0 puntos: Evita métodos prompt() y alert() para evitar interrupciones durante el procesamiento y actualización del DOM, y emplea adecuadamente la información estática del proyecto. Considerar las alternativas propuestas en el comentario al uso de alert en el código.

- **Legibilidad (1 punto)**
✅ 0.5 puntos: Los nombres de variables, funciones y objetos son significativos para el contexto.
❌ 0  puntos: Las instrucciones se escriben de forma legible y se emplean comentarios oportunos, manteniendo el código fuente ordenado en términos de declaración y secuencia. En algún punto el código hace demasiadas cosas, considero que con la clase `Carrito.js` se va solucionar, así como la simplificación de algunas funciones y el desarrollo de algunas auxiliares. Lo mismo sucede con el código comentado, analizar alguna de las posibles soluciones propuestas.

- **GitHub (2 puntos):**
✅ 0.5 puntos: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
❌ 0 puntos: Creación de una rama "feature/cuarta-entrega" a partir de la rama "develop" utilizando Git. Cuidado que la rama marca este aviso `This branch is [7 commits ahead of](https://github.com/JuanOrtizz/Programacion_Web_I_Mate-Style/tree/feature/cuarta-entrega) master.` No queda nada más que verificar la proxima vez desde donde se parte el origen de la rama para crear otra, que debeía ser develop.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/tercera-entrega" con "develop" en GitHub. 

**Nota: 8(ocho)**

2024-11-26 20:53 UTC, JuanOrtizz commented on script.js
> +//FUNCIONES QUE SE AGREGARAN CUANDO EXISTA EL PANEL ADMIN
Realizado

2024-11-26 20:53 UTC, JuanOrtizz commented on script.js
> +    if(emailElemento, mdpElemento, totalElemento){
realizado

2024-11-26 20:53 UTC, JuanOrtizz commented on script.js
> +        alert("El precio mínimo debe ser un número mayor o igual a 0")
Realizado, ahora se usan modales para los filtros de precio y para cuando se quiere comprar y el carrito esta vacio

2024-11-26 20:54 UTC, JuanOrtizz commented on script.js
> +    let productosFiltrados = false
realizado

2024-11-26 20:54 UTC, JuanOrtizz commented on script.js
> +    const patron = /^[^\s@]+@[^\s@]+\.[^\s@]+$/ // patron regex para comprabar esto con el test
gracias por la recomendacion profe. Realizado

2024-11-26 20:54 UTC, JuanOrtizz commented on script.js
> +function inputTelefono(texto){
se realizado en cada una de las funciones con el return if else

2024-11-26 20:54 UTC, JuanOrtizz commented on script.js
> +const carrito = JSON.parse(localStorage.getItem('carrito')) || []
Clase realizada con sus respectivos metodos

2024-11-26 20:55 UTC, JuanOrtizz commented on script.js
> +        const nombre = nombreFormulario.value
Funciones auxiliares realizadas y una funcion general que agrupa todas y devuelve un valor booleano para validar los campos

2024-11-26 20:57 UTC, JuanOrtizz commented
@MVelasquez98 Solicito el LGTM, realice todos los cambios solicitados, comentandole en cada uno lo realizado. Tambien cambie los productos para que sea mas facil de probar los filtros y por ultimo tambien agregue la funcionalidad de settear la cantidad del mismo producto en el carrito, evitando asi que sea repetitivo el mismo producto si se agrega varias veces. Saludos!

2024-11-26 23:38 UTC, MVelasquez98 approved these changes
LGTM

2024-11-27 12:18 UTC, merged