Release/segundo parcial
JuanOrtizz/Programacion_Web_I_Mate-Style pull request #7
Opened 2024-11-28 03:10 UTC by JuanOrtizz

# Entrega 2do Parcial
Hola profe, a continuación dejo la PR de la rama release/segundo-parcial, contra la rama master.
Ademas de este mensaje de PR realizado con el template se visualiza todo lo que realice en la entrega. En el código se puede ver con comentarios que realiza cada cosa. En esta entrega se lleva a cabo la implementación de AJAX, JSON y fetch principalmente.

---

## ¿Qué se está haciendo?
1. **¿Qué problema resuelve?**: 
#### Asincronía y Manejo de Datos
-  Utilizarás AJAX y JSON para obtener datos de forma asíncrona, implementando herramientas como promises y fetch para consumir APIs. Se recomienda usar APIs como: JSONPlaceholder - Mockaroo - Beeceptor - MockAPI - TheCocktailDB - FakeStoreAPI - TheMealDB - TheMovieDB
- También puedes utilizar un archivo JSON estático incluido en el proyecto, incluyendo dentro de una carpeta “api”.
- La información estática o obtenida de una API debe cargarse y utilizarse de forma asíncrona.
- Implementa un recorrido óptimo de las colecciones utilizando funciones de orden superior (map, filter, reduce, etc.).
- Captura entradas del usuario mediante inputs y eventos adecuados.
- Las salidas deben ser coherentes con las entradas y presentarse en el HTML de forma asíncrona.

2. **¿Como lo resuelve?**: 
- **Archivo JSON Estatico**:Donde obtengo informacion estatica desde un archivo local `productos.json` ubicado dentro de una carpeta `api/` para cargar los productos que anteriormente estaban en el HTML. Ahora estan almacenados en el JSON, donde tiene cada uno su categoria correspondiente que luego con una funcion de orden superior **filter** filtramos por su categoria para cargar en la pagina HTML a la que corresponden. Todo esto se realiza con una **funcion async y con atributos await**.
- **Filtrado por precios**: También se realizan filtrados de la misma manera para mostrar productos en un rango de precio, usando la funcion **filter**, obteniendo los precios que ingresa el usuario por los input del filtro y modificando el **DOM** en base a esto.
- **Datos obteneidos de API mockAPI:** Usando una API de `mockAPI` obtengo leyendas (frases), que al realizar la compra se muestran modificando el DOM, de una pagina nueva intermedia mientras se realiza la compra. En esta se muestra una barra de progreso mientras se confirma la compra (simulando una interaccion con el backend) con su funcion en el archivo `script.js` para ir aumentando su progreso. Luego redirecciona a la pagina de compra realizada con la informacion ingresada por el usuario en el formulario de compra. En esta se usa map para devolver un arreglo unicamente de las frases y no de los ID, que luego con una funcion de Math hacemos que salga por cada compra una random entre las 5 frases 

---

## Checklist (Antes de solicitar la revisión):
- [X] El código se probó de manera local con éxito.
- [ ] Se escribieron pruebas automatizadas relevantes.
- [X] La documentación fue actualizada (si aplica).
- [x] Este cambio no afecta negativamente a funcionalidades existentes.
- [x] No existen errores conocidos asociados a este cambio.

---

## Información adicional
- **Notas para el revisor**:  
1. **Creacion de archivo CHANGELOG.MD:** Se creo el archivo `changelog.md` con todos las entregas realizadas.
2. **Creacion de directorio .github que contiene pull_request_template.md:** Se creo el archivo `pull_request_template.md` con la plantilla para las PR.
3. **Se agregaron reglas en el repositorio**: Se agregaron reglas para bloquear push directos a las ramas develop y master. Se permiten únicamente mediante pull requests. Ademas se requiere al menos un revisor aprobado para realizar merges en el
repositorio.

---

## Capturas de pantalla:
- Antes redireccionaba al apretar el boton comprar desde `carrito_pago.html` hacia `pago_realizado.html`. Ahora redirecciona a una pagina `pantalla_carga_compra.html` y cuando la barra de carga se completa recien ahi redirecciona a `pago_realizado.html`
![image](https://github.com/user-attachments/assets/a14b7265-58a0-4fac-8d5a-bad038007382)

- **Adjunto imagenes con las reglas del repositorio para las ramas `master` y `develop`:** 
![image](https://github.com/user-attachments/assets/7eaac9e4-9b3e-4701-b97f-18b5fd3347dc)
![image](https://github.com/user-attachments/assets/598107f8-ebc0-47d5-9504-7108dfbacc76)

2024-11-30 19:36 UTC, MVelasquez98 commented on CHANGELOG.MD
Muy completo. Muy bueno

2024-11-30 20:00 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA**:
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Asincronía y Manejo de Datos (3 puntos)**
✅ 1 punto: Utiliza AJAX y JSON para obtener datos de forma asíncrona, manejando adecuadamente promises y fetch para consumir alguna API mock .
✅ 1 punto: La información estática esta en formato JSON, se carga y utiliza de manera asíncrona.
✅ 1 punto: Recorrido de colecciones siendo óptimo utilizando funciones de orden superior. No aplica porque no usa AJAX ni JSON

- **Gestión del Proyecto y Buenas Prácticas con GitHub (7 puntos)**:
✅ 1 punto: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
✅ 1 punto: Creación de una rama release/segundo-parcial a partir de la rama develop utilizando Git.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama feature/cuarta-entrega con develop en GitHub.
✅ 1 punto: Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama release/segundo-parcial como parte de la entrega.
✅ 1 punto: Implementa un archivo [CHANGELOG.md](https://github.com/Laboratoria/changelog-guide) documentando los cambios realizados en el proyecto en cada entrega o versión, siguiendo un formato estructurado. Revisar cambios propuestos, algo más completo. Tomar el comentario solo como modelo, rellenar correctamente.
✅  1 punto: Configura [reglas en GitHub](https://docs.github.com/es/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) para bloquear push directos a las ramas develop y master, exigiendo pull requests con al menos un revisor aprobado para realizar merges. Incluir en el comentario de la pull request una captura con el estado de las reglas.
✅ 1 punto: Implementa una [plantilla (template) de pull request](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) en el repositorio para estandarizar las solicitudes de revisión y asegurarse de incluir in[formación relevante](https://axolo.co/blog/p/part-3-github-pull-request-template) (descripción, cambios realizados, pruebas realizadas, etc.). 

**Nota**: 10(Diez)

**Comentarios**:  ¡Felicidades por alcanzar un puntaje perfecto de 10! Demostraste habilidades excepcionales en la gestión de proyectos y en la implementación técnica. Lograste estructurar y gestionar tu proyecto de manera eficiente, y estoy seguro de que este enfoque te va beneficiar en futuros proyectos laborales y academicos también. ¡Exitos con tu presentación final!

2024-11-30 20:00 UTC, MVelasquez98 commented on script.js
> +let mdpPagoRealizado = sessionStorage.getItem('mdp')
Usa `const` en lugar de `let` para `mdpPagoRealizado`, ya que no necesitas modificar el tipo de valor después. Si planeas cambiar su contenido posteriormente, está bien usar let, pero si solo necesitas declarar y no cambiar el tipo, let no es la mejor elección.
```suggestion
const mdpPagoRealizado = sessionStorage.getItem('mdp')
```

2024-11-30 20:00 UTC, MVelasquez98 commented on script.js
> +    fetch("https://67474f1a38c8741641d64755.mockapi.io/frases")
Implementa el control de errores utilizando try-catch para manejar posibles problemas al cargar datos de la API.
```suggestion
       try {
        const response = await fetch("https://67474f1a38c8741641d64755.mockapi.io/frases");
        if (!response.ok) throw new Error('Error en la carga: ' + response.status);
        const data = await response.json();
        const frases = data.map(item => item.frase);
        crearFraseDeCompra(frases);
    } catch (error) {
        console.error("Error al cargar las frases:", error);
   }

```

2024-11-30 20:00 UTC, MVelasquez98 commented on Carrito.js
> +            for (let producto of this.productos) {
Usa reduce en lugar de un bucle for para sumar los precios de los productos. Esto es más conciso y expresivo, optimizando el recorrido de las colecciones con funciones de orden superior.
```suggestion
           return this.productos
        .reduce((total, producto) => total + producto.precio * producto.cantidad, 0)
        .toFixed(2)
```

2024-12-02 03:01 UTC, JuanOrtizz commented on Carrito.js
> +            for (let producto of this.productos) {
Gracias por la recomendación profe, funciona perfecto!

2024-12-02 03:08 UTC, JuanOrtizz commented on script.js
> +let mdpPagoRealizado = sessionStorage.getItem('mdp')
Si, usaba let para cambiarle el valor numerico recibido por el option del select que seleccionaba el usuario. Ahora agregue una variable dentro `medioDePago` y esa se asigna al DOM con un `textContent = medioDePago` dependiendo la opcion del usuario.

2024-12-02 03:15 UTC, JuanOrtizz commented
>[!NOTE]
> Hola @MVelasquez98, gracias por el comentario y por las recomendaciones! Ya realice los cambios con sus sugerencias y solicito el LGTM.
>Buena semana, saludos😄!

2024-12-02 12:43 UTC, MVelasquez98 approved these changes
LGTM

2024-12-14 18:53 UTC, merged